import type { ParsedGraph } from './graph-types';

export const WALMART_SAMPLE: ParsedGraph = {
  nodes: [
    { id: 'n1', label: 'Walmart Inc.', type: 'COMPANY', description: 'American multinational retail corporation', sourceId: 'walmart_10k_fy2023', degree: 8 },
    { id: 'n2', label: 'Net Revenue FY2023', type: 'FINANCIAL_METRIC', description: '$611.3B total revenue for fiscal year 2023', sourceId: 'consolidated_income', degree: 6 },
    { id: 'n3', label: 'Net Revenue FY2022', type: 'FINANCIAL_METRIC', description: '$572.8B total revenue for fiscal year 2022', sourceId: 'consolidated_income', degree: 5 },
    { id: 'n4', label: 'Walmart US', type: 'SEGMENT', description: 'Domestic retail segment, largest contributor to revenue', sourceId: 'segment_reporting', degree: 7 },
    { id: 'n5', label: 'Walmart International', type: 'SEGMENT', description: 'International retail operations across 19 markets', sourceId: 'segment_reporting', degree: 5 },
    { id: 'n6', label: "Sam's Club", type: 'SEGMENT', description: 'Membership-only warehouse club segment', sourceId: 'segment_reporting', degree: 4 },
    { id: 'n7', label: 'Doug McMillon', type: 'PERSON', description: 'President and CEO of Walmart Inc.', sourceId: 'proxy_statement', degree: 3 },
    { id: 'n8', label: 'Operating Income FY2023', type: 'FINANCIAL_METRIC', description: '$20.6B consolidated operating income', sourceId: 'consolidated_income', degree: 4 },
    { id: 'n9', label: 'Supply Chain Risk', type: 'RISK_FACTOR', description: 'Disruptions to global supply chain affecting inventory and costs', sourceId: 'risk_factors', degree: 3 },
    { id: 'n10', label: 'eCommerce Growth', type: 'CONCEPT', description: 'Global eCommerce sales grew 24% YoY in FY2023', sourceId: 'business_overview', degree: 5 },
    { id: 'n11', label: 'India', type: 'GEOGRAPHIC_REGION', description: 'Key international market via Flipkart acquisition', sourceId: 'international_segment', degree: 3 },
    { id: 'n12', label: 'Flipkart', type: 'COMPANY', description: 'Indian eCommerce platform, Walmart subsidiary', sourceId: 'international_segment', degree: 4 },
    { id: 'n13', label: 'Gross Profit Margin FY2023', type: 'FINANCIAL_METRIC', description: '24.0% gross margin vs 24.4% in FY2022', sourceId: 'consolidated_income', degree: 3 },
    { id: 'n14', label: 'Inventory FY2023', type: 'FINANCIAL_METRIC', description: '$56.5B inventory, down 2.7% from FY2022', sourceId: 'balance_sheet', degree: 3 },
    { id: 'n15', label: 'SEC', type: 'REGULATORY_BODY', description: 'US Securities and Exchange Commission', sourceId: '10k_filing', degree: 2 },
  ],
  edges: [
    { source: 'n1', target: 'n2', label: 'REPORTED', weight: 0.95 },
    { source: 'n1', target: 'n3', label: 'REPORTED', weight: 0.95 },
    { source: 'n2', target: 'n3', label: 'COMPARED_TO', weight: 0.9 },
    { source: 'n1', target: 'n4', label: 'HAS_SEGMENT', weight: 0.98 },
    { source: 'n1', target: 'n5', label: 'HAS_SEGMENT', weight: 0.98 },
    { source: 'n1', target: 'n6', label: 'HAS_SEGMENT', weight: 0.98 },
    { source: 'n7', target: 'n1', label: 'LEADS', weight: 0.99 },
    { source: 'n1', target: 'n8', label: 'REPORTED', weight: 0.92 },
    { source: 'n9', target: 'n1', label: 'AFFECTS', weight: 0.7 },
    { source: 'n10', target: 'n4', label: 'DRIVES', weight: 0.85 },
    { source: 'n10', target: 'n5', label: 'DRIVES', weight: 0.8 },
    { source: 'n5', target: 'n11', label: 'OPERATES_IN', weight: 0.88 },
    { source: 'n12', target: 'n11', label: 'HEADQUARTERED_IN', weight: 0.95 },
    { source: 'n1', target: 'n12', label: 'OWNS', weight: 0.97 },
    { source: 'n1', target: 'n13', label: 'REPORTED', weight: 0.9 },
    { source: 'n1', target: 'n14', label: 'REPORTED', weight: 0.88 },
    { source: 'n15', target: 'n1', label: 'REGULATES', weight: 0.99 },
    { source: 'n13', target: 'n3', label: 'DERIVED_FROM', weight: 0.95 },
  ],
  metadata: {
    nodeCount: 15, edgeCount: 18,
    sourceName: 'walmart_10k_fy2023',
    entityTypes: { COMPANY: 2, FINANCIAL_METRIC: 5, SEGMENT: 3, PERSON: 1, RISK_FACTOR: 1, CONCEPT: 1, GEOGRAPHIC_REGION: 1, REGULATORY_BODY: 1 },
  },
};
